repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.2.2
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [ python, pyi, jupyter ]
        args: [ --fix ]
      # Run the formatter.
      - id: ruff-format
        types_or: [ python, pyi, jupyter ]
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
    -   id: check-added-large-files
    -   id: check-json
    -   id: check-merge-conflict
    -   id: end-of-file-fixer
    -   id: requirements-txt-fixer
    # -   id: check-yaml
    -   id: detect-aws-credentials
    -   id: detect-private-key
